### ISSUE TITLE
Mappa Campagna Antincendio Boschivo 2017

### ISSUE THREAD

**Issue by gbvitrano** [emergenzeHack/italiaafuoco#14]
Da quest'articolo di repubblica http://www.repubblica.it/cronaca/2017/07/17/news/la_mappa_degli_incendi_in_italia-170967420/
Mi è venuto in mente di rifare la mappa dei mezzi e basi aeree della Campagna Antincendio Boschivo 2017
http://www.protezionecivile.gov.it/jcms/it/view_dossier.wp?contentId=DOS64456

Ancora non è completa, spero di entro oggi.
http://u.osmfr.org/m/159107/

Può essere utile al progetto?

**Comment by aborruso** [comment]
@gbvitrano  standing ovation!

**Comment by gbvitrano** [comment]
![mappa_basi_mezzi_1024](https://user-images.githubusercontent.com/20488693/28378701-5fcc94a6-6cb1-11e7-809e-60b06386b765.jpg)

Completa!
http://u.osmfr.org/m/159107/

**Comment by gbvitrano** [comment]
hem... ho provato a fare un Pull Request per creare un post per il blog... spero sia andato a buon fine.
Fatemi sapere

**Comment by iltempe** [comment]
@gbvitrano un mito! ho appena fatto il merge. eccola qua!! http://italiaafuoco.info/2017-07-19-mappa-flotta-aerea-protezione-civile/ unica nota: ricentra un po' la mappa UMAP in modo che sia centrata sull'italia . grazie!!!

**Comment by gbvitrano** [comment]
ricentrata :-) 
Ps. Ottima guida la tua :-)
