### ISSUE TITLE
Ringraziamenti pagina About sul sito

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/italiaafuoco#17]
So che non è fondamentale ma è brutto e dall'idea di un sito non curato il fatto che nella pagina ci sia il paragrafo dei ringraziamenti vuoto ma con la precisazione: _(i ringraziamenti sono in progress ogni giorno….Non avertene a male se non compari ancora, grazie lo stesso!)_
Togliamo tutto o inseriamo dei ringraziamenti....

**Comment by iltempe** [comment]
io non ringrazierei nessuno e son disposto a togliere anche il mio nome. nessun problema per me.

**Comment by cristigalas** [comment]
@iltempe ma figurati, ci mancherebbe! Basta togliere il titoletto Credits e la frase tra parentesi...

**Comment by iltempe** [comment]
rimosso. fatemi sapere, se vogliamo anche togliere i nostri nomi tolgo tutto.

**Comment by cristigalas** [comment]
@iltempe va benissimo così! Chiudo.
