### ISSUE TITLE
Catasti terre bruciate

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/italiaafuoco#19]
Come sapete, il catasto delle terre bruciate è uno strumento essenziale per ridurre il rischio di incendi dolosi e tutti i Comuni italiani dovrebbero averle e invece sembra lo abbia [solo un Comune su 5](https://www.avvenire.it/attualita/pagine/un-comune-su-5-senza-il-catasto) e spesso non aggiornato e monitorato. 
Non so se ci avete già pensato e in tal caso perdonatemi, ma spulciando da 'cittadina' su Dati.gov.it e cercando con le parole chiave incendi/incendio/fuoco/particelle catastali vengono fuori i catasti delle terre bruciate di un po' di Comuni e della Regione Sardegna (e tra l'altro sembra che la Sardegna sia proprio una delle regioni dove monitorare e aggiornare il catasto è più difficile). 
Allora mi sono chiesta, e vi chiedo, potremmo trasformare quei dati in mappe? Avere mappe delle terre bruciate che tutti possono consultare aiuterebbe a monitorare il territorio e a rendere davvero utile il catasto.

**Comment by aborruso** [comment]
Ciao @cristigalas non ho guardato i dataset, ma immagino che siano cartografici, quindi le mappe si dovrebbero poter fare.

Ti rispondo però con un rilancio: forse quello che potrebbe fare questo progetto è sottolineare come esistano pochissimi dati sulle terre bruciate, nonostante siano un obbligo di legge. Potremmo provare a fare un censimento e/o fare partire delle richieste di accesso e/o FOIA (con gli amici di FOIAPop magari)?
Fare insomma una campagna sulla cosa.
L'ho scritta male e a caldo

**Comment by cristigalas** [comment]
Ottima proposta @aborruso! Ora ci ragiono, cerco di capire se ci sono dei dati per un eventuale censimento e parlo con Giuseppe dell'eventuale campagna Foia! Ci aggiorniamo, intanto se voi volete dare un'occhiata a quei dati...

**Comment by iltempe** [comment]
quoto @aborruso. putroppo attualmente cercando "incendi" su dati.gov.it viene fuori questo http://www.dati.gov.it/search/type/dataset?query=incendi%20 . pochi dati, solo 6 organizzazioni, alcuni link non funzionano e parecchi dei dataset presenti non sono aggiornati. situazione direi quasi al limite del sopportabile visto cosa sta accadendo. un'azione di richiesta apertura e aggiornamento dati sarebbe ottima cosa secondo me

**Comment by cristigalas** [comment]
@iltempe se cerchi anche con fuoco e incendio ne vengono fuori un po' di più ma ovviamente sempre pochi e come dici tu la cosa è davvero insopportabile! Sì, dobbiamo fare una campagna Foia, ne parlerò a Giuseppe...

**Comment by iltempe** [comment]
@cristigalas non so chi sia Giuseppe ma va benissimo ;-)

**Comment by cristigalas** [comment]
Ho parlato con Giuseppe che si è detto disponibilissimo a lavorarci. Raccogliamo un po' di idee e info e vi aggiorniamo...

**Comment by iltempe** [comment]
Bene! @aborruso proponeva un MODELLO di richiesta dati che ognuno possa adottare da inviare alle proprie PA. mi pare una buona idea. che ne dite?

**Comment by giuragu** [comment]
Eccomi, Ciao!
Sono io il Giuseppe di cui parla Cristina :)
Condivido pienamente l'iniziativa e vi ringrazio per avermi chiamato in causa. Come dice Cristina ora raccogliamo un po' di info e fonti in generale. Mi faccio anche un'idea di massima anche giuridica così da avere più chiaro come strutturare la richiesta tipo e come possiamo utilizzare foiapop.it

**Comment by gpirrotta** [comment]
Ciao a tutti,
mi inserisco anch'io nella discussione, rispondendo così anche all'email di @iltempe che mi segnalava questo thread.
Mi chiedo e vi chiedo se per generare il modello di richiesta dati di cui parla @aborruso è possibile utilizzare il template già presente su foiapop.it. Mi spiego meglio.

Foiapop mette a disposizione delle API con le quali è possibile passare delle informazioni di partenza, da cui iniziare la generazione della richiesta di accesso civico generalizzato.

Ad esempio, con la seguente API:

`http://www.foiapop.it/api/accesso-civico-generalizzato?cf=CODICE-FISCALE-DELLA-PA&dati=DATI-DA-INSERIRE-NELLA-RICHIESTA ` 

è possibile creare link/bottoni su siti esterni, passando nel campo **dati** la richiesta dell'accesso civico generalizzato, che ad esempio potrebbe essere:
*Richiesta dataset catasto terre bruciate* o qualsiasi altra richiesta, anche molto lunga.

Ovviamente il **cf** dovrà essere valorizzato con il codice fiscale della PA e, a questo punto, Foiapop disporrà di tutti i campi necessari per generare la richiesta di accesso civico generalizzato, secondo il template standard.

Può già bastare questa funzionalità di foiapop per ciò che avevate in mente o pensavate invece ad un modello dati più articolato?

**Comment by aborruso** [comment]
@gpirrotta mi piace moltissimo tutto foiapop, ma sopratutto l'aspetto che sottolinei nel tuo messaggio.

Quindi se @giuragu trova la frase semplice (che probabilmente è simile a quella che proponi tu) userei proprio la modalità che proponi.

Tocca comunque un po' studiare la giurisprudenza. Vi scrivo su un altro thread

**Comment by cristigalas** [comment]
Non me ne intendo ma anch'io, dopo aver studiato un po' Foiapop, credo che la proposta di @gpirrotta sia ottima! 
E come dicevo a @giuragu potremmo anche capire se si può in qualche modo fare una ricerca sugli albi pretori per capire quali Comuni pubblicano i catasti delle terre bruciate (che devono essere aggiornati annualmente) visto che la [legge 353/2000](http://www.camera.it/parlam/leggi/00353l.htm) prevede la pubblicazione negli albi pretori. 
Intanto [qui](http://www.wwf.it/regioni_wwf/?31880/Roghi-SiciliaWWF-necessario-aggiornare-Catasto-incendi) un recente appello di Wwf perché i Comuni aggiornino i catasti.

**Comment by iltempe** [comment]
@gpirrotta secondo me è ottima soluzione. Quando avete approfondito scrivici qui se sul sito italiaafuoco ha senso predisporre una pagina che faccia da frontend per Foiapop per passarti i dati tramite le API.

**Comment by gpirrotta** [comment]
Ciao a tutti,
ritorno sulla discussione relativa alle API di FOIAPop.
Per la richiesta dei catasti delle terre bruciate @giuragu consiglia di procedere con l'accesso civico generalizzato piuttosto che con quello semplice. 
A questo aggiungerò nelle API di FoiaPop il parametro **richiesta**

Ad esempio per il comune di Palermo:
**cf**= 80016350821
**dati** = l'art. 10 comma 2, Legge 353 del 2000 
(il testo passato in **dati** comparità nel pdf dopo **VISTO**)

**richiesta** = 
(1) La pubblicazione dell’elenco e delle relative perimetrazioni dei soprassuoli già percorsi dal fuoco nell'ultimo quinquennio come previsti dall’art 10 comma 2 della Legge 353/2000; (2) La relativa pubblicazione in albo pretorio comunale se non già fatto; (3) La pubblicazione in amministrazione trasparente nella sezione Amministrazione Trasparente/Pianificazione e Governo del Territorio se non già fatto e dopo aver adempiuto alla pubblicazione in albo pretorio, se non già effettuata, ritenendo l'adempimento un atto di governo del territorio di cui all’art. 39 comma 1 del D. Lgs. 33/2012
  
(il testo passato in **richiesta** comparità nel pdf dopo **CHIEDE** (**non ancora implementato**)

L'API da generare sarà quindi:

`http://www.foiapop.it/api/accesso-civico-generalizzato?cf=80016350821&dati=l%27articolo+10%2C+comma+2+della+Legge+353%2F200+che+definisce+l%27obbligo+per+i+comuni+di+provvedere+a+censire%2C+tramite+apposito+catasto%2C+i+soprassuoli+gi%C3%A0+percorsi+dal+fuoco+nell%27ultimo+quinquennio%2C+tramite+elenco+e+relative+perimetrazioni&richiesta=%281%29+La+pubblicazione+dell%E2%80%99elenco+e+delle+relative+perimetrazioni+dei+soprassuoli+gi%C3%A0+percorsi+dal+fuoco+nell%27ultimo+quinquennio+come+previsti+dall%E2%80%99art+10+comma+2+della+Legge+353%2F2000%3B+%282%29+La+relativa+pubblicazione+in+albo+pretorio+comunale+se+non+gi%C3%A0+fatto%3B+%283%29+La+pubblicazione+in+amministrazione+trasparente+nella+sezione+Amministrazione+Trasparente%2FPianificazione+e+Governo+del+Territorio+se+non+gi%C3%A0+fatto+e+dopo+aver+adempiuto+alla+pubblicazione+in+albo+pretorio%2C+se+non+gi%C3%A0+effettuata%2C+ritenendo+l%27adempimento+un+atto+di+governo+del+territorio+di+cui+all%E2%80%99art.+39+comma+1+del+D.+Lgs.+33%2F2 `

@iltempe 
Per quanto riguarda l'uso dell'API lato client, **italiaafuoco** dovrebbe agganciarsi a FOIAPop tramite un frontend che, attraverso una tendina (o autocompletamento) di tutti i comuni presi da IPA, sia in grado di generare l'API di cui sopra.

Al click del bottone FOIAPop mostrerà il form per l'inserimento dell'anagrafica dell'utente e successivamente il PDF generato con i dati desiderati.

Vi faccio sapere appena la feature verrà implementata.
Ciao

**Comment by gpirrotta** [comment]
@iltempe @aborruso 
La feature è online.

Per questa tipologia di richiesta ritengo sia più utile utilizzare **solo** il parametro **richiesta** senza il parametro **dati** come descritto nel mio precedente commento.

L'URL da generare a questo punto diventa:

`http://www.foiapop.it/api/accesso-civico-generalizzato?cf=80016350821&richiesta=%281%29+La+pubblicazione+dell%E2%80%99elenco+e+delle+relative+perimetrazioni+dei+soprassuoli+gi%C3%A0+percorsi+dal+fuoco+nell%27ultimo+quinquennio+come+previsti+dall%E2%80%99art+10+comma+2+della+Legge+353%2F2000%3B+%282%29+La+relativa+pubblicazione+in+albo+pretorio+comunale+se+non+gi%C3%A0+fatto%3B+%283%29+La+pubblicazione+in+amministrazione+trasparente+nella+sezione+Amministrazione+Trasparente%2FPianificazione+e+Governo+del+Territorio+se+non+gi%C3%A0+fatto+e+dopo+aver+adempiuto+alla+pubblicazione+in+albo+pretorio%2C+se+non+gi%C3%A0+effettuata%2C+ritenendo+l%27adempimento+un+atto+di+governo+del+territorio+di+cui+all%E2%80%99art.+39+comma+1+del+D.+Lgs.+33%2F2012`

Qui il [link](http://www.foiapop.it/api/accesso-civico-generalizzato?cf=80016350821&richiesta=%281%29+La+pubblicazione+dell%E2%80%99elenco+e+delle+relative+perimetrazioni+dei+soprassuoli+gi%C3%A0+percorsi+dal+fuoco+nell%27ultimo+quinquennio+come+previsti+dall%E2%80%99art+10+comma+2+della+Legge+353%2F2000%3B+%282%29+La+relativa+pubblicazione+in+albo+pretorio+comunale+se+non+gi%C3%A0+fatto%3B+%283%29+La+pubblicazione+in+amministrazione+trasparente+nella+sezione+Amministrazione+Trasparente%2FPianificazione+e+Governo+del+Territorio+se+non+gi%C3%A0+fatto+e+dopo+aver+adempiuto+alla+pubblicazione+in+albo+pretorio%2C+se+non+gi%C3%A0+effettuata%2C+ritenendo+l%27adempimento+un+atto+di+governo+del+territorio+di+cui+all%E2%80%99art.+39+comma+1+del+D.+Lgs.+33%2F2012)

ciao

**Comment by iltempe** [comment]
@gpirrotta grande! domanda ma è possibile parametrizzare i dati del form di richiesta per usarlo pr altri comuni di italia? cioè l'url che hai postato è modificabile?

**Comment by gpirrotta** [comment]
@iltempe 
L'URL:
`http://www.foiapop.it/api/accesso-civico-generalizzato?`

è modificabile nel seguente modo:

**cf**: codice fiscale dell'ente, preso da IPA **(campo obbligatorio)**
**dati**: è il testo che apparirà nel PDF subito dopo il **VISTA**  (opzionale)
**richiesta**: è il testo che apparirà nel PDF subito dopo il **CHIEDE** (opzionale)

**Comment by iltempe** [comment]
ottimo! cosa possiamo usare come front-end per generare il link? Un semplice Google Form? che dite?

**Comment by gpirrotta** [comment]
@iltempe 
Dato che italiaafuoco gira su jekyll e dopo aver letto il tuo [articolo](https://iltempe.github.io/blog/2017/08/05/generare-siti-da-dataset.html) la prima cosa che mi viene in mente è di sfruttare questa funzionalità nativa di jekyll per importare direttamente il CSV di tutti i comuni italiani in una tendina di un form su una pagina Jekyll.

Immaginando ad esempio un file **ipa.csv** dentro la directory **_data** con due intestazioni di colonna **comune** e **cf**, per generare l'URL di FOIAPop ad ogni cambio della selezione del comune nella tendina, posso scrivere ad esempio:

```
<form>
<select name="ipa">
{% for member in site.data.ipa %}
<option value="{{member.cf}}">
{{ member.comune }}
</option>
{% endfor %}
</select>
</form>


<a class="foia" target="_blank" id="foia" href="">
Crea Foia
</a>

<script>
$('select').on('change', function() {
  href = 'http://www.foiapop.it/api/accesso-civico-generalizzato?cf=&richiesta=%281%29+La+pubblicazione+dell%E2%80%99elenco+e+delle+relative+perimetrazioni+dei+soprassuoli+gi%C3%A0+percorsi+dal+fuoco+nell%27ultimo+quinquennio+come+previsti+dall%E2%80%99art+10+comma+2+della+Legge+353%2F2000%3B+%282%29+La+relativa+pubblicazione+in+albo+pretorio+comunale+se+non+gi%C3%A0+fatto%3B+%283%29+La+pubblicazione+in+amministrazione+trasparente+nella+sezione+Amministrazione+Trasparente%2FPianificazione+e+Governo+del+Territorio+se+non+gi%C3%A0+fatto+e+dopo+aver+adempiuto+alla+pubblicazione+in+albo+pretorio%2C+se+non+gi%C3%A0+effettuata%2C+ritenendo+l%27adempimento+un+atto+di+governo+del+territorio+di+cui+all%E2%80%99art.+39+comma+1+del+D.+Lgs.+33%2F2012'
  newhref = href.replace('cf=','cf='+ this.value);
  $('.foia').attr('href', newhref);
})
</script>
```
Certo rimane la pesantezza di caricare 8000 comuni italiani su un'unica pagina statica.

my2c
ciao

**Comment by iltempe** [comment]
@gpirrotta interessante. Potremmo fare una serie di pagine una per ogni regione. Pesantezza? una volta fatto il build è fatto!!!

**Comment by gpirrotta** [comment]
@iltempe 
forse mi sono espresso male, intendevo *pesantezza* di apertura pagina lato utente cioè ogni utente dovrà aprire sul proprio browser una pagina con una *select* contenente 8000 comuni. 
Tuttavia l'idea di avere una pagina per regione mi sembra un buon compromesso per *spalmare* gli 8000 comuni su più pagine e migliorare l'efficienza del servizio a meno che non si voglia usare l'**autocomplete**.

**Comment by iltempe** [comment]
@gpirrotta possiamo in ogni caso paginare i dati, cioè se la preoccupazione è di avere una sola pagina con troppi dati, possiamo impostarne al massimo 20 per pagina e gestirla in pagine successive. La pesantezza in termini di navigazione in realtà essendo tutto statico non dovrebbe essere un problema....non credi?

**Comment by gpirrotta** [comment]
@iltempe 
ho verificato le dimensioni del file **ipa.csv** e considerando i campi necessari (nome comune e codice fiscale) ottengo un file di dimensione **280KB**.
Onestamente pensavo fosse più grande il CSV per cui, dopo questa verifica, il mio consiglio è, a meno di ulteriori considerazioni, di inserire i valori dei comuni in una **select** su un' **unica** pagina, al fine di poter generare l'URL corretto per FOIAPop.

Un'ulteriore ottimizzazione potrebbe essere quella di aggiungere, subito dopo il nome del comune, il nome della provincia tra parentesi.

**Comment by iltempe** [comment]
ok @gpirrotta , dimmi che devo fare su italiaafuoco. da che parte si comincia...come si procede?

**Comment by gpirrotta** [comment]
@iltempe 
vedi #52

**Comment by iltempe** [comment]
@gpirrotta grande! http://italiaafuoco.info/foia/

**Comment by giuragu** [comment]
Ciao @cristigalas @iltempe @aborruso @gpirrotta oggi dopo pranzo potrò dedicare due orette alla campagna. Nel senso che potrei fare un riesame generale, vedere cosa manca, se ci sono cose da modificare o meno per partire. Avete dei dubbi sulla validità del testo, qualcosa da mettere sul tavolo prima del lancio? @cristigalas @dontyna per il comunicato stampa ci sentiamo sulla issue #50

**Comment by iltempe** [comment]
@giuragu io aspetto che siate voi a lanciare. poi posso divulgare.

**Comment by giuragu** [comment]
ok @iltempe. Grazie mille. Scusaci comunque se il tutto è stato sospeso per colpa nostra.
Ho rivisto il testo della pagina foia e inoltrato questa [pull request](https://github.com/emergenzeHack/italiaafuoco/pull/53). Come ti sembra l'integrazione?
Lavoriamo intanto al comunicato sulla issue #50.

**Comment by giuragu** [comment]
Anche qui @cristigalas Chiariti gli obblighi, inviato il comunicato stampa, prodotto [post specifico](http://italiaafuoco.info/2017-08-30-campagna_foia_catasto_incendi/). Propongo di chiudere la issue @cristigalas  e passiamo alla seconda fase :)

**Comment by cristigalas** [comment]
Evvai! Chiudo.
