### ISSUE TITLE
Piccolo test con i dati dell'incendio del Vesuvio

### ISSUE THREAD

**Issue by gbvitrano** [emergenzeHack/italiaafuoco#20]
Con i dati [EMSR213: Forest Fire in Southern Italy](http://emergency.copernicus.eu/mapping/list-of-components/EMSR213) ho provato a fare questo piccala test, se l'idea vi piace si può applicare a tutti i dataset.
Per farla ho usato Qgis e due pluging principali Qgis2web Qgis2threej e  Sidebar-v2 (suggerito @aborruso) per il layout delle pagine html
La prossima settimana spero di avere il tempo di elaborare i dati della Sicilia e di scrivere un post :-)

<a href="http://siciliahub.github.io/mappe/EMSR213/Vesuvio/index.html"><img width="1000" src="http://siciliahub.github.io/mappe/EMSR213/Vesuvio/legend/vesuvio_1024.jpg" Title=" L'incendio Vesuvio, una situazione drammatica vista da COPERNICUS - Emergency Management Service" /></a>

[**L'incendio Vesuvio, una situazione drammatica vista da COPERNICUS - Emergency Management Service**](http://siciliahub.github.io/mappe/EMSR213/Vesuvio/index.html)

**Comment by iltempe** [comment]
@gbvitrano mi pare ottimo. come preferisci, puoi fare un post e metterlo nella sezione blog o mappe. oppure se credi anche uno per ogni mappa che elabori, insomma piena libertà.

**Comment by gbvitrano** [comment]
ok grazie :-)
