### ISSUE TITLE
Invio automatico su Telegram news DPC su incendi

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/italiaafuoco#23]
Credo possa essere utile fare, come nel caso di TCI, l'invio automatico sul canale Telegram (ed eventualmente anche su Twitter) delle news e comunicati riguardanti gli incendi pubblicati sul sito del Dip. nazionale Protezione Civile. Che ne dite?

**Comment by aborruso** [comment]
ok, domani provo a lavorarci

**Comment by aborruso** [comment]
ecco feed RSS sui comunicati PC sugli incendi http://feeds.feedburner.com/comunistampaincendipc

@iltempe ci pensi tu all'automazione per la pubblicazione in automatico sui vari canali?

**Comment by iltempe** [comment]
@aborruso fatto. collegato il feed a twitter e telegram. ora monitoro e vedo come va.

**Comment by cristigalas** [comment]
@iltempe su Twitter è ok, su Telegram invece va cambiato il testo, risultano tutti uguali :(

**Comment by cristigalas** [comment]
@iltempe metterei oltre che hashtag #italiaafuoco anche parola #incendi che su Twitter è hashtag più usato.

**Comment by iltempe** [comment]
fatto un po' di correzioni. monitoriamo e vediamo come va.

**Comment by aborruso** [comment]
@iltempe @cristigalas potrebbe arrivare un'altra (ma solo una volta) mitragliata di avvisi.

La formattazione dei post  non dipendeva da me, ma la mitragliata sì: non mi ero accorto del delirio degli URL generati sul sito della PC, in cui ogni URL ha associata la sessione di navigazione  e quindi lo stesso URL diciamo che cambia nel tempo e quindi cambia il guid (l'id del RSS) e quindi il trigger IFTTT parte.

Ci sono due possibilità: o piccola nuova mitragliata (perché ho modificato il codice e quindi verranno generati guid corretti (ma diversi) o @iltempe  deve cancellare le ricette IFTTT e ricrearle.

Che mi dite?

**Comment by iltempe** [comment]
@aborruso ricreo le ricette io no problem. posso farlo adesso?

**Comment by aborruso** [comment]
@iltempe yes, cancella le precedenti

**Comment by cristigalas** [comment]
Ok @aborruso @iltempe intanto io ho ripulito Telegram e chiesto scusa agli iscritti al canale ;)

**Comment by aborruso** [comment]
@cristigalas sei la solita certezza!!

**Comment by iltempe** [comment]
@aborruso @cristigalas fatto. cancellate le ricette e ricreate.

**Comment by cristigalas** [comment]
@iltempe @aborruso su Telegram mi pare che adesso sia tutto ok! L'unica cosa è che, se possibile, aggiungerei un hashtag #ProtezioneCivile per far capire meglio la fonte e il fatto che non sono post nostri, visto che dal link non si evince (come invece accade per TCI).

**Comment by iltempe** [comment]
#ProtezioneCivile inserito.

**Comment by cristigalas** [comment]
@iltempe accidenti che efficienza! 😃😜
