### ISSUE TITLE
Form Segnala

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/italiaafuoco#24]
Non so se è qui che debba porre la questione ma non saprei dove altro farlo... vorrei sapere qualcosa di più sulla form Segnala: viene usata? Nel caso, dove finiscono le segnalazioni e come vengono gestite? Lo chiedo perché non ho capito se la form è bene promuoverla e invitare le persone ad usarla. Se qualcuno su Twitter ci segnala un incendio non sarebbe bene rimandarlo alla form? Insomma avrei bisogno di qualche lume ;)

**Comment by aborruso** [comment]
Ciao @cristigalas il form ad oggi non è stato usato da utenti. Funziona e produce issue qui: https://github.com/emergenzeHack/italiaafuoco_segnalazioni

Io rimanderei al form come tu dici

**Comment by cristigalas** [comment]
Ciao @aborruso! Siamo sicuri che funziona? Perché non vedo (o non trovo ;) la segnalazione che ho inviato io qualche giorno fa...

**Comment by aborruso** [comment]
@cristigalas è [questa](https://github.com/emergenzeHack/italiaafuoco_segnalazioni/issues/15)?

**Comment by cristigalas** [comment]
@aborruso sì! Ma non c'è scritto nulla! E invece avevo inserito descrizione, foto, link a tweet, ecc. come mai?

**Comment by aborruso** [comment]
@cristigalas ho appena fatto un [test](https://github.com/emergenzeHack/italiaafuoco_segnalazioni/issues/16) e sembra ok.

Ne fai ancora uno tu?

**Comment by cristigalas** [comment]
Scusa @aborruso ho fatto nuova segnalazione ma non la trovo... in quale cartella devo guardare? Non è che non sono abilitata a vederle? O sono proprio io imbranata?
E poi mi domandavo come si visualizzerebbe se pubblicata sul sito? Secondo me, se vogliamo che qualcuno usi la form, dovremmo aprire una sezione dedicata sul sito visibile a tutti. Incentiverebbe l'uso della form. 
Infine nella form aggiungerei un avviso che invita chi avvista un incendio a darne subito comunicazione alle autorità competenti chiamando 115 o il 112. Un modo anche per ribadire che non ci sostituiamo alle istituzioni. Che ne dici @iltempe?

**Comment by aborruso** [comment]
Ciao @cristigalas della tua segnalazione non c'è traccia. È come se ci fosse un problema di compatibilità. Che browser usi? Se hai più di un browser, fai una prova con un altro browser?

Io per il form mi sono fermato ai miei task: mostrare come crearne uno e attivare lo script che trasformasse le segnalazioni in issue.

**Comment by cristigalas** [comment]
@aborruso uso chrome per IPad. Provo con safari... chiediamo aiuto a @iltempe per il resto?

**Comment by cristigalas** [comment]
@aborruso con Safari funziona ma il campo link rimane vuoto nonostante io abbia inserito indirizzo...

**Comment by iltempe** [comment]
eccomi scusate leggo solo ora... c'è rimasto qualcosa da fare? modificare il form?

**Comment by cristigalas** [comment]
@iltempe c'è qualche problema nella compilazione della form via chrome per iPad e poi suggerivo di aggiungere nella form un avviso che invita chi avvista un incendio a darne subito comunicazione alle autorità competenti chiamando 115 o il 112. Mi chiedevo, infine, se fosse utile prevedere sul sito una sezione dove si possono visualizzare le segnalazioni. Vorrei promuovere su Twitter e Telegram la form e vedere sul sito pubblicate le segnalazioni credo ne stimolerebbe l'uso... Che ne dici?

**Comment by aborruso** [comment]
@cristigalas il link viene registrato, ma è stato aggiunto da @iltempe  dopo che avevo fatto la prima versione dello script; devo solo modificare il codice per mostrarlo anche nelle issue.

Spero di farlo domani

**Comment by Pinzauti** [comment]
Non so se avete risolto, in ogni caso se ce ne fosse necessità mi rendo disponibile a riadattare/aggiornare il form usato per terremotocentroitalia

**Comment by cristigalas** [comment]
@Pinzauti Non credo sia stato risolto da @iltempe e poi sarebbe importante aggiungere la frase sull'avvisare le autorità competenti qualora si avvistassero incendi.

**Comment by iltempe** [comment]
no scusate, io qui mi sono perso. Non ho capito se lato form devo ancora fare qualcosa o no.

**Comment by cristigalas** [comment]
Non so se chi tra @iltempe o @Pinzauti debba/possa intervenire ma urgono tre interventi sulla form:
1. rendere visibile il campo link nella issue prodotta dalla form compilata
2. Rendere la form compatibile con Chrome per IPad e non so se anche con altri browser
3. aggiungere nella form l'invito a chi avvista un incendio a darne subito comunicazione al 115 o 112.

**Comment by aborruso** [comment]
@cristigalas 

- [x] "rendere visibile il campo link nella issue prodotta dalla form compilata" > me ne occupo io
- [x] "Rendere la form compatibile con Chrome per IPad e non so se anche con altri browser" > non dipende da noi, stiamo usando un servizio hosted, posso provare ad aprire una issue
- [x] aggiungere nella form l'invito a chi avvista un incendio a darne subito comunicazione al 115 o 112 > o lo modifica @iltempe o se mi da accesso ci penso io

**Comment by iltempe** [comment]
@aborruso se hai accesso al form vai libero. dato che hai lo script sottomano è meglio che lo gestisci tu col form direttamente almeno li tieni sempre allineati. grazie
