### ISSUE TITLE
Sezione Press sul sito

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/italiaafuoco#26]
Forse bisognerebbe creare sul sito una sezione Press e cominciare ad archiviare i vari articoli e servizi che escono sul progetto...

**Comment by iltempe** [comment]
Si giusto. Faccio io stasera.

**Comment by iltempe** [comment]
Pagina press creata e collegata al menu in alto sotto la voce "il progetto". http://italiaafuoco.info/press/
Per popolarla è sufficiente editare [questo](https://github.com/emergenzeHack/italiaafuoco/blob/master/_data/press.csv) file CSV aggiungendo una riga con i 4 campi necessari:

- data
- fonte del press
- titolo del press
- link al press

La modifica può essere fatta facilmente anche online cliccando sull'apposita "matita" che github mette a disposizione per modificare i file da interfaccia e "committando" le modifiche.

**Comment by cristigalas** [comment]
Ok @iltempe provo a inserire qualcosa... ma basta cliccare sulla matita e inserire le info di seguito?

**Comment by cristigalas** [comment]
@iltempe ci ho provato ma non riesco, forse non sono abilitata?

**Comment by iltempe** [comment]
prova ora.

**Comment by cristigalas** [comment]
Fatto! 😃
