### ISSUE TITLE
Invio automatico su Telegram e Twitter comunicati Vigili del fuoco

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/italiaafuoco#27]
Sul sito dei vigili del fuoco c'è una sezione chiamata [L'Italia colpita dai roghi](http://www.vigilfuoco.it/aspx/notizia.aspx?codnews=42337) con aggiornamenti quasi giornalieri sugli interventi effettuati. Sarebbe secondo voi possibile inviarli sui nostri profili Telegram e Twitter? Tanto più che queste sono info che non danno attraverso il loro account Twitter e rimangono lì sepolte...  O comunque se non questi aggiornamenti, le news (vedi notiziario) che riguardano gli incendi?

**Comment by iltempe** [comment]
il problema è che come spesso accade non sono feed...e non sono dati. Ci sarebbe da analizzare un po' la cosa e capire se è possibile strutturarle per inviarle in modo automatico.

**Comment by aborruso** [comment]
@iltempe guarda che nemmeno i comunicati sugli incendi della PC hanno un feed :)

Ecco quello per i vigili del fuoco http://feeds.feedburner.com/italiacolpitafuocoVF

**Comment by iltempe** [comment]
ahhhhhahahhahahahahahah! si lo sapevo intendevo dire che se si vuole tirare fuori i contenuti andava un minimo elaborato qualcosa che "visitasse" ogni singola pagina. Mi ero scordato che tu sei il mago del "bruciatore di feed". ok metto su le ricette IFTTT.

**Comment by iltempe** [comment]
fatto. pubblicazione automatica su twitter e telegram a posto

**Comment by cristigalas** [comment]
Wow! Grandi @aborruso @iltempe! Ora vediamo come vengono pubblicati...

**Comment by aborruso** [comment]
@cristigalas sembra funzionare: hai avuto proprio una buona idea, perché sono dati nascosti
