### ISSUE TITLE
Dati del Corpo Forestale dello Stato via Datiallefiamme.it

### ISSUE THREAD

**Issue by giuragu** [emergenzeHack/italiaafuoco#34]
@iltempe @aborruso @cristigalas A proposito di dataset potrei rendere disponibile l'elenco da cui ha origine [questo lavoro di analisi](http://datiallefiamme.it/) che già conoscete ;)
Purtroppo il sito del corpo forestale dello stato non esiste più poiché istituzione inglobata nell'Arma dei Carabinieri. E la fonte dati è attualmente "dispersa" :( Ma non demordiamo :)

Che ne pensate?
In che modo questa analisi pensate possa tornare utile per italiaafuoco?

**Comment by iltempe** [comment]
per me può essere utilissimo. pensavo di mettere in piedi una pagina opendata dove elencare i dataset raccolti o prodotti (vedi  #31 ). Una semplice tabella dei dataset stile quella fatta [qui](http://terremotocentroitalia.info/opendata/) dove indicare i link ai dati e specificare una licenza di riuso.

**Comment by giuragu** [comment]
Bene Matteo. Grazie! Mi sembra una buona idea. Allora preparo il dataset e ti aggiorno

**Comment by cristigalas** [comment]
@giuragu @iltempe ottima idea metterli in una sezione dedicata a #opendata e fonti dati... semmai distinguerei tra dataset diciamo già pronti e disponibili e dati/info che invece sono 'sepolti' e che noi in qualche modo abbiamo tirato fuori o comunque resi in qualche modo fruibili, come nel caso dei comunicati DPC, le news dei Vigili del fuoco, i dati del Ministero Ambiente sugli incendi nei parchi... Credo che evidenziare la differenza possa aiutare a capire meglio quanto siano importanti i dati aperti e il lavoro di civic hacking che proponiamo.

**Comment by giuragu** [comment]
Ho inserito il dataset nel repository e quindi anche in elenco [opendata.csv](https://github.com/emergenzeHack/italiaafuoco/blob/master/_data/opendata.csv).
@cristigalas chiudo la issue e ripropongo il tuo commento nella issue #31
