### ISSUE TITLE
Mappa incendi Sicilia con i dati EFFIS

### ISSUE THREAD

**Issue by gbvitrano** [emergenzeHack/italiaafuoco#36]
Perdonate l'assenza, ma in questi giorni sto lavorando/giocando a ricostruire la mappa degli incendi in Sicilia rilevati da [COPERNICUS](http://emergency.copernicus.eu/mapping/list-of-components/EMSR213)
Finalmente ho trovato un layout responsive che vada a bene per Leaflet e per me :-)
La struttura funziona, ma i dati sono ancora incompleti. 

Solo il quadrante 06 e 07 rispettivamente San Vito Lo Capo e Monreale sono completi. Spero di completarla al più presto!

La mappa index rappresenta un quadro d'unione, e ogni area è cliccabile!
La mappa si può navigare sia dai menù in alto (header) che dal menu che si trova nell'icona dei layer in alto a destra di tutte le mappe.
Si può cambiare base cartografica selezionando l'icona globo, posta sotto l'icona dei layer

<a href="http://siciliahub.github.io/mappe/EMSR213/incendi_sicilia/index.html"><img width="1000" src="http://siciliahub.github.io/mappe/EMSR213/incendi_sicilia/legend/Sicilia_1024.jpg" Title="Mappa incendi Sicilia con i dati EFFIS -  COPERNICUS - Emergency Management Service" /></a>

[**Mappa incendi Sicilia con i dati EFFIS -  COPERNICUS - Emergency Management Service**](http://siciliahub.github.io/mappe/EMSR213/incendi_sicilia/index.html)

**Comment by iltempe** [comment]
gran lavoro. ma te l'ho già detto. vedi tu quando e come metterlo online. forse la cosa migliore è fare un post in categoria mappe, ma è solo un consiglio, decidi tu la forma migliore quando la cosa è pronta

**Comment by gbvitrano** [comment]
Grazie :-)
si, appena lo completo, lo faccio.

**Comment by iltempe** [comment]
ci linki la bozza di post qui?

**Comment by gbvitrano** [comment]
Questo è quello che avevo scritto 

https://docs.google.com/document/d/17Pbw0uFGMLnSKARTv8cqx0B5LvCaih3QEqe71HIiKt0/edit?usp=sharing

**Comment by iltempe** [comment]
ho rivisto il post, l'ho reso un po' più "snello" in alcune frasi per i non tecnici della materia, ma in sostanza non ho cambiato nulla. Ho aggiunto chi ha realizzato la mappa citandoti assieme ad opendatasicilia. Se mi dai un ok e il codice da embeddare possiamo fare un markdown e il post sul sito https://docs.google.com/document/d/1mqAPxNxk4xOvl7lRQA-jT7qC2xHJjjTf8cxpu38MwU8/edit?usp=sharing

**Comment by gbvitrano** [comment]
Per me va bene :-) grazie 

questo è il  codice per inserire la mappa

<iframe width="100%" height="900px" frameBorder="0" src="http://siciliahub.github.io/mappe/EMSR213/incendi_sicilia/index.html"></iframe><p><a href="http://siciliahub.github.io/mappe/EMSR213/incendi_sicilia/index.html" title="Incendi Sicilia, COPERNICUS - Emergency Management - EMSR213: Forest Fire in Southern Italy - Sicilia, su base opendata">Visualizza a schermo intero</a></p>

**Comment by iltempe** [comment]
sei online. a te l'onore di divulgare http://italiaafuoco.info/2017-07-28-mappa-incendi-sicilia/ quando vuoi. io aspetto te per rilanciare ;-) intanto chiudo issue.

**Comment by gbvitrano** [comment]
Lo lancio domani mattina?

**Comment by iltempe** [comment]
certo benissimo domani!

**Comment by gbvitrano** [comment]
ok , grazie grazie
