### ISSUE TITLE
Feed lanci Ansa su incendi

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/italiaafuoco#37]
Sul sito Ansa c'è una sezione dedicata agli incendi, questa qui http://www.ansa.it/ricerca/ansait/search.shtml?tag=Incendi+dolosi e mi domandavo se anche in questo caso non si possa estrarre un feed e pubblicarlo in automatico su Twitter e Telegram. E poi aggiungerlo anche nella sezione fonti di dati...

**Comment by aborruso** [comment]
@cristigalas è fattibile e me lo sono assegnato.

**Comment by cristigalas** [comment]
Ottimo! Grazie @aborruso mago dei feed!! 
Ps. In realtà ho visto che proprio oggi hanno rinominato la categoria in "incendio", qui il link http://www.ansa.it/ricerca/ansait/search.shtml?tag=Incendio#

**Comment by aborruso** [comment]
@cristigalas eccolo http://feeds.feedburner.com/ansaitincendi

@iltempe prima di attivare qualsiasi cosa, mi ci abbonerei con un feed reader per vedere come va

**Comment by cristigalas** [comment]
@aborruso wow! Io l'ho già inserito nel mio Feedly!

**Comment by aborruso** [comment]
Faccio presente che su ANSA `© Copyright ANSA - Tutti i diritti riservati`.

Non possiamo sicuramente dire che il feed espone dati aperti  e non lo dobbiamo mettere tra i dati aperti.
Lo usiamo come servizio informativo, punto.

**Comment by cristigalas** [comment]
Sì sì certo! Eventualmente lo possiamo inserire in una generica sezione "fonti informative", che dici?

**Comment by iltempe** [comment]
ok. perfetto. che dite creiamo le ricette per tweet e telegram?

**Comment by cristigalas** [comment]
@iltempe a me pare funzionare, quindi proverei l'invio automatico su Twitter e Telegram...

**Comment by iltempe** [comment]
fatto. chiudo.
