### ISSUE TITLE
Errore Build Sito

### ISSUE THREAD

**Issue by iltempe** [emergenzeHack/italiaafuoco#42]
Ragazzi stasera non riesco più a fare build in locale del sito..mi da questo errore

jekyll 3.3.0 | Error:  Unquoted fields do not allow \r or \n (line 1).

Fino a ieri nessun problema. Vi viene in mente qualche modifica fatta oggi che può essere collegata a questo? ho fatto un paio di commit adesso ma a causa di questo problema non compaiono.

**Comment by aborruso** [comment]
@iltempe sì, il file CSV modificato da Giuseppe Ragusa. Penso sia quello

**Comment by iltempe** [comment]
ho provato a rimuovere la linea inserita da lui ma da sempre lo stesso errore. In locale a te da lo stesso errore?

**Comment by iltempe** [comment]
ok dovrei aver risolto facendo un revert e riportando le modifiche di gragusa. chiudo. grazie.
