### ISSUE TITLE
Articolo inserito in press.csv ma non ancora pubblicato

### ISSUE THREAD

**Issue by giuragu** [emergenzeHack/italiaafuoco#46]
@cristigalas Stamattina ha inserito in Press articolo su Cittadini di Twitter ma ancora non è pubblicato sul sito eppure è qui https://github.com/emergenzeHack/italiaafuoco/blob/master/_data/press.csv

**Comment by iltempe** [comment]
mi assegno questo issue.

**Comment by cristigalas** [comment]
@iltempe anche @giuragu aveva problemi di visualizzazione con campo "Utilizzo" in pagina opendata, vedi #31

**Comment by iltempe** [comment]
@cristigalas @giuragu ho risolto. Il problema consisteva nel fatto che avendo @giuragu inserito il CSV del dataset del 2009 nella folder _data del sito veniva compilato da jekyll (ed il build falliva) perchè il dataset non è "conforme" al formato dati che jekyll si aspetta come input. Ho mosso per il momento quel file all'esterno della cartella, riconfigurato il link ed ora sempra essere tutto ok. Ho anche riformattato il file PRESS e OPENDATA in formato yml anzichè CSV, la struttura è semplice da editare basta fare attenzione a "" e a non mettere spazi inutili al termine delle righe. In questo modo si vede meglio se i file fossero compilati male. Chiudo Issue.
