### ISSUE TITLE
Mappa incendi boschivi dal 2009 a maggio 2016

### ISSUE THREAD

**Issue by gbvitrano** [emergenzeHack/italiaafuoco#49]
Approfittando dei dati del lavoro di @giuragu [dati alle fiamme](http://datiallefiamme.it/) sto rielaborando i dati per costruire una mappa degli incendi dal 2009 a maggio 2016
Ancora non completa, devo aggiungere la mappa delle superficie percorsa dal fuoco, e un'altra mappa sugli incendi in Sicilia, grazie ai dati di @aborruso 

<a href="http://siciliahub.github.io/mappe/datiallefiamme/index.html#6/41.656/12.239"><img width="1000" src="http://siciliahub.github.io/mappe/datiallefiamme/legend/mappa_incendi_1024.jpg" Title="Mappa incendi boschivi dal 2009 a maggio 2016" /></a>

- [**Mappa incendi boschivi dal 2009 a maggio 2016**](http://siciliahub.github.io/mappe/datiallefiamme/index.html#6/41.656/12.239)

**Comment by giuragu** [comment]
Grazie @gbvitrano! 
Aggiornamento dati 2016: Chissà che non si riesca ad ottenere questo pdf scovato su via archive.org dove ci sarebbero i dati al 27/11/2016 mentre noi li abbiamo fino al maggio 2016
[http://web.archive.org/web/20170124085348/http://www.corpoforestale.it:80/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/6358](http://web.archive.org/web/20170124085348/http://www.corpoforestale.it:80/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/6358)
@aborruso @iltempe al link arrivo ma il pdf è da un'altra parte e non si scarica....Voi che dite?

**Comment by gbvitrano** [comment]
@giuragu ci vorrebbe un po di testo (riassunto del tuo lavoro) da mettere anche nella sidebar della mappa, ci pensi tu o faccio copia/incolla dal tuo sito :-)

**Comment by giuragu** [comment]
@gbvitrano fai pure tu :) Poi casomai se c'è da modificare/aggiungere ti dico

**Comment by gbvitrano** [comment]
note 3 

![note_iii_360x640](https://user-images.githubusercontent.com/20488693/28901059-f7074d76-77f5-11e7-9a46-39c46c4445fc.jpg)
![note_iii_640x360](https://user-images.githubusercontent.com/20488693/28901061-f9136bf4-77f5-11e7-8c72-f9e8ba729875.jpg)

iPad_mini
![ipad_mini_1024_768](https://user-images.githubusercontent.com/20488693/28901067-070b0c12-77f6-11e7-9449-b6f6427e83fa.jpg)

16:9
![test_16_9](https://user-images.githubusercontent.com/20488693/28901081-1334a0fc-77f6-11e7-8579-df8bd1580e1a.jpg)

4:3
![test_4_3](https://user-images.githubusercontent.com/20488693/28901105-32bea3e6-77f6-11e7-9e40-eb3f03123ac6.jpg)

Adesso si adatta un pò ovunque.

**Comment by iltempe** [comment]
molto ben fatto. complimentoni.

**Comment by gbvitrano** [comment]
Piccolo problema... dai dati di datiallefiamme.it in Sicilia dal 2009 a maggio 2016 ci sono stati 6.504 incendi. Caricando i file di @aborruso in totale mi ritrovo 3039 poligoni, teoricamente sono poco meno della metà.
Guardando il sito [SIF](http://sif.regione.sicilia.it/webgis/(F(A0C748A9560373BAED7AD5C3F8AA0E6D7D96C3C58C715172CDF7AED25A7C22877ECBC263F82880BCA4B014D800DF8657D4EE674FD7F001F9F4A91BBC2285BAF3E01EC3C35C60A83F700590E429AC37647987B4DDA9C42BA2E479AF5B5C30E75861E3891435FE963AFA054755D80CA0F8C5237B3F))/webgis.aspx) ad occhio si vedono poligoni in più rispetto a quelli abbiamo noi.

**Un esempio con gli incendi del 2010** 

Poligoni caricati in qgis
![test_qgis_01](https://user-images.githubusercontent.com/20488693/29002757-f87c35d4-7aa9-11e7-86c2-c67dc7ee4e30.jpg)

Le aree cerchiate nel [SIF](http://sif.regione.sicilia.it/webgis/(F(A0C748A9560373BAED7AD5C3F8AA0E6D7D96C3C58C715172CDF7AED25A7C22877ECBC263F82880BCA4B014D800DF8657D4EE674FD7F001F9F4A91BBC2285BAF3E01EC3C35C60A83F700590E429AC37647987B4DDA9C42BA2E479AF5B5C30E75861E3891435FE963AFA054755D80CA0F8C5237B3F))/webgis.aspx) non sono presenti nei nostri file. 

![test_qgis_02](https://user-images.githubusercontent.com/20488693/29002759-101fb3c8-7aaa-11e7-9b26-0f186f4cc7f3.jpg)

Cosa si fà? 
con i dati corretti sarebbe venuta fuori una bella mappa :-)

**Comment by gbvitrano** [comment]
Con i dati che avevo ho provato a fare una mappa densità, si potrebbero fare 1000 cose ma vale la pena farli con i dati parziali? 
![sicilia](https://user-images.githubusercontent.com/20488693/29005370-6b48ae14-7ada-11e7-88b0-f13105482cb1.jpg)

[link](https://goo.gl/P9LXEw)

**Comment by gbvitrano** [comment]
Con i dati che avevo ho provato a fare una mappa densità, si potrebbero fare 1000 cose ma vale la pena farli con i dati parziali? 
![sicilia](https://user-images.githubusercontent.com/20488693/29005370-6b48ae14-7ada-11e7-88b0-f13105482cb1.jpg)

[link](https://goo.gl/P9LXEw)

**Comment by gbvitrano** [comment]
ho fatto qualche modifica alle mappe della sicilia
![mappa_densita_sicilia](https://user-images.githubusercontent.com/20488693/29036629-7dffa906-7ba0-11e7-9fa5-43a1bcd32083.jpg)

ho inserito anche le aree censite, anche se i dati sono parziali, ho lasciato come info solo Provincia, Comune, Località ed anno dell'incendio

![mappa_censimento](https://user-images.githubusercontent.com/20488693/29036703-c831aa60-7ba0-11e7-8590-1c9a0778a618.jpg)

**Comment by gbvitrano** [comment]
per @giuragu ti ho preparato un file zip con screenshot delle mappe e grafici se ti possono essere utili per il post

questo è il codice da inserire nel post per far caricare la mappa, l'iframe è settato per un'altezza di 900px , la puoi regolare a tuo piacere modificando il parametro **height="900px"**

`<iframe width="100%" height="900px" frameBorder="0" src="http://siciliahub.github.io/mappe/datiallefiamme/index.html"></iframe><p><a href="http://siciliahub.github.io/mappe/datiallefiamme/index.html" title="Incendi boschivi dal 2009 a maggio 2016 in Italia, su base opendata">Visualizza a schermo intero</a></p>`

Ditemi se ci sono correzioni da fare, sicuramente qualcosa mi sarà sfuggita :-)

**Comment by giuragu** [comment]
Il post di presentazione è stato pubblicato [qui](http://italiaafuoco.info/2017-08-28-dati_e_mappe_ex_Corpo_Forestale_dello_Stato/).
La mappa è [qui](http://siciliahub.github.io/mappe/datiallefiamme/index.html#6/41.673/12.239)

@gbvitrano a te la valutazione sulla chiusura di questa issue :)

**Comment by gbvitrano** [comment]
Grazie a tutti ☺
