### ISSUE TITLE
Problemi di visualizzazione nella condivisione sui social 

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/italiaafuoco#5]
Quando si condivide l'indirizzo web http://www.italiaafuoco.info sui Social, ad esempio su un post Telegram, compare l'iconcina di TerremotoCentroItalia e non di Italiaafuoco!

**Comment by Pinzauti** [comment]
Dai vari debugger (Facebook e Twitter) sembra andare tutto bene, forse era solo da fare lo scraping del nuovo link. Unico problema è la dimensione dell'immagine su Facebook (l'icona del fuoco viene visualizzata solo in parte) e il link di condivisione che rimanda a http://italiaafuoco.matteofortini.it invece che a http://italiaafuoco.info.
Ho fatto una pull per risolvere.

Qui come appare su Facebook:
![capture 1](https://user-images.githubusercontent.com/16691846/28261340-0f3043b8-6adf-11e7-967c-16bd55487a3f.PNG)

Qui su Twitter:
![capture](https://user-images.githubusercontent.com/16691846/28261341-0f388a1e-6adf-11e7-8004-a4406ef476c1.PNG)

**Comment by cristigalas** [comment]
Su Telegram continua a comparire l'icona di TCI... 
![img_4892](https://user-images.githubusercontent.com/21283775/28279826-064106f0-6b22-11e7-94a2-24aca09ebd6d.PNG)

**Comment by Pinzauti** [comment]
Adesso dovrebbe andare anche su Telegram.
Per chi non lo conoscesse segnalo [@WebpageBot](https://telegram.me/webpagebot) per aggiornare le preview dei link in Telegram.
![capture](https://user-images.githubusercontent.com/16691846/28330980-c16fadaa-6bef-11e7-8fb7-78c686ec0829.PNG)

**Comment by cristigalas** [comment]
Sì funziona!! Grazie!

**Comment by cristigalas** [comment]
Chiudo issue @Pinzauti?

**Comment by Pinzauti** [comment]
Sisi va bene
