### ISSUE TITLE
Comunicato stampa campagna accesso civico catasti incendi

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/italiaafuoco#50]
Dopo ferragosto vorremmo lanciare una campagna Foia per chiedere ai Comuni di pubblicare i catasti delle terre bruciate negli albi pretori, così come prevede la legge, e in Amministrazione Trasparente. @giuragu ci sta lavorando, vedi issue #19 e #25.
Per dare più risalto alla campagna pensavamo ad un comunicato stampa che Donata potrebbe aiutarci a scrivere e ad inviare urbi et orbi. Per impostarlo servirebbe un testo dal quale partire che spieghi un po' la cosa...

**Comment by iltempe** [comment]
@dontyna hai massima libertà sul tema. ovviamente è un modo per impiegare il tuo ferragosto che altrimenti non avresti saputo come impiegare ;-)

**Comment by dontyna** [comment]
@cristigalas c'è già un comunicato / un testo che racconta cos'è ItaliaAFuoco?

**Comment by cristigalas** [comment]
@dontyna c'è il testo sul sito...poca roba e quel che hanno scritto alcune testate, vedi in press (io sono fuori in questi giorni e ti posso aiutare poco, mi dispiace...)

**Comment by giuragu** [comment]
Ciao @dontyna e @cristigalas.
Scrivo qui quasi come appunto. WWF e Legambiente si sono recentemente espresse sul tema catasto incendi. Il primo con una [news](http://www.wwf.it/regioni_wwf/?31880/Roghi-SiciliaWWF-necessario-aggiornare-Catasto-incendi), il secondo nel [dossier incendi 2017](https://www.legambiente.it/sites/default/files/docs/dossier_incendi_27_07_2017.pdf). Quando questo comunicato sarà pronto potremmo fargli un segnale

**Comment by giuragu** [comment]
@cristigalas @dontyna buongiorno! Abbiamo una bozza su cui si sta lavorando?

**Comment by cristigalas** [comment]
Ciao @giuragu! Non so se @dontyna abbia già preparato qualcosa, comunque io eventualmente nel fine settimana posso lavorarci. Eventualmente tu puoi scrivere un testo che spieghi un po' la cosa da usare come base per il comunicato e da pubblicare sul sito dove c'è già la pagina pronta per la richiesta Foia?

**Comment by giuragu** [comment]
ok @cristigalas nel frattempo ho aggiunto[ un piccolo paragrafo](http://italiaafuoco.info/foia/) che chiarisce già meglio l'utilità del tutto con riferimento alla normativa. Formattato meglio darebbe già un senso compiuto molto efficace. 
Posso aggiungere ancora in basso prima del form una cosa tipo "clicca su crea richiesta, aggiungi solo i tuoi dati, il testo della richiesta è già precompilato, e andando avanti potrai visionare una anteprima nonchè le istruzioni per il successivo invio al Comune. Infine un click su Crea Richiesta Foia ed ecco il tuo pdf da scaricare". Nel frattempo ho notato che va chiarito meglio che il sito non invia la richiesta ma la produce. Per evitare qualsiasi dubbio in merito....Ok?

**Comment by cristigalas** [comment]
Ottimo @giuragu! Oltre al testo prima della form di cui scrivi, aggiungerei senz'altro la precisazione che il sistema genera la richiesta ma non la invia. Eventualmente aggiungerei anche 2 righe per spiegare come inviarla. Infine aggiungerei il link alla legge che rimanda al testo.

**Comment by giuragu** [comment]
Eccomi di nuovo @cristigalas. 
Ho reso più chiaro nel testo che la funzione è quella di creare la richiesta. Ho previsto quindi altri due paragrafi (come funziona e come inviare successivamente la richiesta al comune). Ho quindi inserito il link alla legge 353/2000. 
La modifica è in [approvazione](https://github.com/emergenzeHack/italiaafuoco/pull/54).

**Comment by cristigalas** [comment]
Grazie @giuragu! Mi sembra che ci sia tutto, sistemerei solo la formattazione del titolo "Come funziona" che compare non in grassetto con tre ### e toglierei lo spazio tra il testo e il titolo "Il successivo invio al Comune". Infine non so se è il caso di spiegare brevemente tra parentesi il significato di "firma olografica" (o in alternativa rimandare a Wikipedia o altro). Che ne dici?
Intanto provo a sentire @dontyna per capire se aveva già lavorato al comunicato stampa...

**Comment by dontyna** [comment]
ciao cari @cristigalas e @giuragu, eccomi. No, non ho ancora lavorato alla bozza, ho acceso il pc solo oggi dopo due settimane di pausa. Volevo capire: oltre al comunicato come volete muovervi per la campagna? Cioè, il punto centrale della notizia è raccontare che ItaliaaFuoco permette ai cittadini di creare richieste Foia o che vuole coinvolgere i comuni?

**Comment by giuragu** [comment]
Ciao @dontyna bentornata anche tu :). Sulla tua domanda: la prima che hai detto. Nel senso che ItaliaAfuoco tramite un servizio messo a disposizione da FoiaPop promuove una campagna di accesso civico sui comuni cercando di coinvolgere più cittadini possibili. Si trova tutto alla pagina [FOIA](http://italiaafuoco.info/foia/). Se puoi fai anche un test, nel senso di provare a creare una richiesta così da avere ancora più chiaro l'oggetto.
@cristigalas ho apportato le correzioni che indicavi. Sulla firma olografa ho aggirato il problema eliminando la parola e scrivendo diversamente. La [pagina](http://italiaafuoco.info/foia/) è aggiornata.

**Comment by dontyna** [comment]
@giuragu se manca un comune è perché non ci sono state segnalazioni a riguardo?

**Comment by giuragu** [comment]
@dontyna no. Hai individuato qualche comune mancante? Quale?

**Comment by giuragu** [comment]
Comunicato ultimato. Spedito a giornali ed associazioni da @dontyna.
Ecco qui il post sul sito: http://italiaafuoco.info/2017-08-30-campagna_foia_catasto_incendi/

**Comment by giuragu** [comment]
Chiariti gli obblighi, inviato il comunicato stampa, prodotto [post specifico](http://italiaafuoco.info/2017-08-30-campagna_foia_catasto_incendi/). Propongo di chiudere la issue @cristigalas

**Comment by cristigalas** [comment]
Chiudo @giuragu!
