### ISSUE TITLE
Integrazione del testo della pagina FOIA

### ISSUE THREAD

**Issue by aborruso** [emergenzeHack/italiaafuoco#67]
Ciao cari,
per me è necessario aggiungere in fondo al testo qualcosa di simile

# Un'ultima cosa

Anzi due 😉:

- se invii una richiesta per il tuo comune - una volta fatto - puoi indicarlo qui (mettere un link a un form o similare)? In questo modo altri utenti sapranno se per un dato comune è già stata fatta una richiesta;
- quando riceverai i dati sui catasti delle terre bruciate , inviacele per favore tramite questo form. Così creeremo un **catalogo centralizzato** dei catasti delle terre bruciate del comune di tuo interesse.

**Comment by dontyna** [comment]
ciao Andy,
da utente "ignorante" io metterei anche una sorta di **Faq** per rispondere alle domande di chi usa per la prima volta lo strumento. 

La tua prima integrazione infatti mi sembra fondamentale, io avrei chiesto "Come faccio a sapere se per quel comune è già stata fatta una richiesta?" :) 
Se siete d'accordo sulle Faq io ne ho già una seconda! E soprattutto, in caso, apro un'altra issue.

**Comment by cristigalas** [comment]
Sì, hai ragione @aborruso, quelle due integrazioni sono necessarie e concordo anche con le FAQ di @dontyna.

**Comment by giuragu** [comment]
Ottima idea @aborruso.
Anch'io d'accordo con @dontyna. Si...sarei per aprire altra issue sul tema FAQ.

**Comment by giuragu** [comment]
@aborruso hai pensato a un gform per segnalare l'invio della richiesta al Comune e l'eventuale risposta?

**Comment by aborruso** [comment]
Ho aggiunto il primo form per raccogliere le segnalazioni di utenti che hanno fatto la richiesta

**Comment by aborruso** [comment]
Ho aggiunto modalità di invio catasti
