### ISSUE TITLE
Problema con invio automatico news vigili del fuoco 

### ISSUE THREAD

**Issue by cristigalas** [emergenzeHack/italiaafuoco#73]
C'è un problema con gli invii automatici delle news dei Vigili del fuoco sul loro sito ci sono fino al 1 settembre mentre, mentre noi li abbiamo su Twitter e Telegram fino al 7 agosto. [Qui la sezione del sito](http://www.vigilfuoco.it/aspx/notizia.aspx?codnews=42920).

**Comment by aborruso** [comment]
Questa era la pagina che non aggiornavano più è che tu segnalasti.
Quando l'hanno ripristinata hanno cambiato URL e lo script si è rotto.
Ora dovrebbe essere ok. Potrebbe partire il.terremoto degli avvisi non passati.

Vediamo che succede.

Grazie cri

**Comment by cristigalas** [comment]
Ok grazie a te Andrea!

**Comment by aborruso** [comment]
Sembra ok, chiudo
