### ISSUE TITLE
Clone mappa

### ISSUE THREAD

**Issue by gbvitrano** [emergenzeHack/italiaafuoco#8]
Nella mappa http://u.osmfr.org/m/158486/ sono riportate le segnalazioni dell'ultima settimana, e tutte le segnalazioni precedenti che fine fanno...?

Ho clonato la mappa ed  ho inserito anche i mesi precedenti, ho visto che i primi incendi vengono segnalati a maggio.
Con un marker nero localizzo le segnalazioni dell'ultima settimana e con il marker bianco i mesi precedenti.
http://u.osmfr.org/m/158685/  spero sia utile

**Comment by iltempe** [comment]
@gbvitrano ma è una figata! la mettiamo sul sito, sai come si fa un post?

**Comment by iltempe** [comment]
@gbvitrano in sostanza devi preparare un file .md prendi spunto dal mio https://github.com/emergenzeHack/italiaafuoco/blob/master/_posts/2017-7-16-mappa-notizie.md

**Comment by gbvitrano** [comment]
Non sapendo dove salvare il file, al momento è salvato sul mio github 
https://github.com/gbvitrano/Maps/blob/master/2017-7-18-new-mappa-notizie.md

---
layout: post
title: La mappa delle news sugli incendi
categories: blog
---

Di seguito la mappa delle notizie relative agli incendi avvenuti nel nostro paese nel cosro del 2017.<br>I marker di colore "**nero**" localizzano gli incendi registrati negli ultimi sette giorni, i marker di colore "**bianco**" localizzano tutte le segnalazioni nemo recenti.<br>Ogni marker sulla mappa riporta la località, il giorno della segnalazione ed un link alla notizia che lo descrive.<br>I dati sono concessi dal progetto [EFFIS - European Forest Fire Information System ](http://effis.jrc.ec.europa.eu/applications/fire-news/) segnalato da [Andrea Borruso](https://twitter.com/aborruso).
[Qui](http://effis.jrc.ec.europa.eu/applications/fire-news/kml/?&country__id__exact=219) il file con tutti i dati aggiornati settimanalmente.

<iframe width="100%" height="900px" frameBorder="0" src="http://umap.openstreetmap.fr/it/map/mappa-delle-news-sugli-incendi_158685?scaleControl=false&miniMap=false&scrollWheelZoom=true&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=caption&captionBar=true"></iframe><p><a href="http://umap.openstreetmap.fr/it/map/mappa-delle-news-sugli-incendi_158685">Visualizza a schermo intero</a></p>

Per una migliore lettura della mappa si può attivare la legenda dei layer, cliccando sul link "**- Informazioni -**" in basso a destra del monitor.

<img width="1000" src="http://github.gbvitrano.it/clip/legenda.jpg" Title="attiva legenda layer" alt="
Italia a Fuoco" /></a>


Spero vada bene :-)

**Comment by iltempe** [comment]
@gbvitrano ottimo! sei online qui http://italiaafuoco.info/2017-07-18-new-mappa-notizie/ divulga pure! per le prossime volte se vuoi puoi fare un fork di questo progetto ed aggiungere post tramite pull request come scritto in questa semplice guida di github http://iltempe.github.io/blog/2016/05/05/primi-passi-con-github.html grazie!!!!

**Comment by gbvitrano** [comment]
Ok, Grazie a te
