### ISSUE TITLE
difficoltà utente nel chiudere segnalazione su "Segnala"

### ISSUE THREAD

**Issue by giuragu** [emergenzeHack/italiaafuoco#80]
Utente mi segnala che mentre prima nel form [Segnala](https://enketo.ona.io/x/#YVUh) i campi sulla latitudine e longitudine prima erano non obbligatori e ora si. Quindi non riesce a chiudere la segnalazione. Era così? è così? @aborruso @iltempe ?

**Comment by aborruso** [comment]
@giuragu è sempre stato obbligatorio.

Si può evitare che lo sia, ma è pensato per segnalare qualcosa in un luogo. Basta indicare un punto nella mappa.

L'utente cosa vuole segnalare?

**Comment by giuragu** [comment]
Direi di chiudere....l'utente informato da me ricordava che prima questa necessità non c'era. Non chiede che venga resa non necessaria
